### ISSUE TITLE
`ModuleNotFoundError: No module named 'impl.shoulder_parser'`

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#177]
While running `./manage.py shoulder-merge-master`, the error:
```
Traceback (most recent call last):
  File "/Users/vieglais/Documents/Projects/ezid/ezid_py3/./manage.py", line 22, in <module>
    main()
  File "/Users/vieglais/Documents/Projects/ezid/ezid_py3/./manage.py", line 18, in main
    django.core.management.execute_from_command_line(sys.argv)
  File "/Users/vieglais/.virtualenvs/ezidpy3/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/vieglais/.virtualenvs/ezidpy3/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/vieglais/.virtualenvs/ezidpy3/lib/python3.9/site-packages/django/core/management/__init__.py", line 257, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/vieglais/.virtualenvs/ezidpy3/lib/python3.9/site-packages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/Users/vieglais/.pyenv/versions/3.9.5/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/vieglais/Documents/Projects/ezid/ezid_py3/ezidapp/management/commands/shoulder-merge-master.py", line 19, in <module>
    import impl.shoulder_parser
ModuleNotFoundError: No module named 'impl.shoulder_parser'
```
is raised.

**Comment by datadavev** [comment]
`shoulder_parser` was removed in a5c25f1 with no explanation.

**Comment by rogerdahl** [comment]
Sorry for the lack of explanation. The `shoulder_parser` module contained the code used for parsing the old master shoulders text file that was used for syncing with N2T. I removed it as part of general cleanup. `shoulder-merge-master` was a one time procedure we used for merging that file into the database. It is no longer needed and should have been removed as well. I've done that now.
