### ISSUE TITLE
link-checker throwing exceptions

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#189]
Link-checker in python3 is throwing exceptions, for example:
```
Jan  7 11:25:51 uc3-ezidui02x2-stg manage.py: ERROR ezidapp.management.commands.proc-link-checker-update proc-link-checker-update 18308 140278829410112 LinkCheckerUpdate: Exception
Jan  7 11:25:51 uc3-ezidui02x2-stg manage.py: Traceback (most recent call last):
Jan  7 11:25:51 uc3-ezidui02x2-stg manage.py: File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/utils/connection.py", line 58, in __getitem__
Jan  7 11:25:51 uc3-ezidui02x2-stg manage.py: return getattr(self._connections, alias)
Jan  7 11:25:51 uc3-ezidui02x2-stg manage.py: File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/asgiref-3.4.1-py3.8.egg/asgiref/local.py", line 107, in __getattr__
Jan  7 11:25:51 uc3-ezidui02x2-stg manage.py: raise AttributeError(f"{self!r} object has no attribute {key!r}")
Jan  7 11:25:51 uc3-ezidui02x2-stg manage.py: AttributeError: <asgiref.local.Local object at 0x7f9528565a30> object has no attribute 'search'
Jan  7 11:25:51 uc3-ezidui02x2-stg manage.py: During handling of the above exception, another exception occurred:
Jan  7 11:25:51 uc3-ezidui02x2-stg manage.py: Traceback (most recent call last):
Jan  7 11:25:51 uc3-ezidui02x2-stg manage.py: File "/apps/ezid/ezid/ezidapp/management/commands/proc-link-checker-update.py", line 78, in run
Jan  7 11:25:51 uc3-ezidui02x2-stg manage.py: with django.db.transaction.atomic(using="search"):
Jan  7 11:25:51 uc3-ezidui02x2-stg manage.py: File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/transaction.py", line 178, in __enter__
Jan  7 11:25:51 uc3-ezidui02x2-stg manage.py: connection = get_connection(self.using)
Jan  7 11:25:51 uc3-ezidui02x2-stg manage.py: File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/transaction.py", line 20, in get_connection
Jan  7 11:25:51 uc3-ezidui02x2-stg manage.py: return connections[using]
Jan  7 11:25:51 uc3-ezidui02x2-stg manage.py: File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/utils/connection.py", line 61, in __getitem__
Jan  7 11:25:51 uc3-ezidui02x2-stg manage.py: raise self.exception_class(f"The connection '{alias}' doesn't exist.")
Jan  7 11:25:51 uc3-ezidui02x2-stg manage.py: django.utils.connection.ConnectionDoesNotExist: The connection 'search' doesn't exist.
Jan  7 11:25:51 uc3-ezidui02x2-stg manage.py: ERROR     root log 18308 140278829410112 LinkCheckerUpdate: - ERROR linkcheck_update._linkcheckUpdateDaemon ConnectionDoesNotExist: The connection 'search' doesn't exist.
```

See also #188

**Comment by datadavev** [comment]
Closed with https://github.com/CDLUC3/ezid/pull/191
