### ISSUE TITLE
proc-datacite continually throwing exceptions after minting a test DOI

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#205]
After minting a DOI as anonymous user and filling all fields, `var/log/ezid/background_jobs/ezid-proc-error.log` reports:

```
an 27 05:24:56 uc3-ezidui02x2-stg ezid-proc-errorlog: DEBUG ezidapp.management.commands.proc_base proc_base 26975 140261853968192 DataCite: Processing task: create
Jan 27 05:24:56 uc3-ezidui02x2-stg ezid-proc-errorlog: ERROR ezidapp.management.commands.proc_base proc_base 26975 140261853968192 DataCite: Task registration error
Jan 27 05:24:56 uc3-ezidui02x2-stg ezid-proc-errorlog: Traceback (most recent call last):
Jan 27 05:24:56 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/apps/ezid/ezid/ezidapp/management/commands/proc_base.py", line 94, in run
Jan 27 05:24:56 uc3-ezidui02x2-stg ezid-proc-errorlog: self.do_task(task_model)
Jan 27 05:24:56 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/apps/ezid/ezid/ezidapp/management/commands/proc_base.py", line 166, in do_task
Jan 27 05:24:56 uc3-ezidui02x2-stg ezid-proc-errorlog: self.create(task_model)
Jan 27 05:24:56 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/apps/ezid/ezid/ezidapp/management/commands/proc-datacite.py", line 25, in create
Jan 27 05:24:56 uc3-ezidui02x2-stg ezid-proc-errorlog: self._overwrite(task_model)
Jan 27 05:24:56 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/apps/ezid/ezid/ezidapp/management/commands/proc-datacite.py", line 44, in _overwrite
Jan 27 05:24:56 uc3-ezidui02x2-stg ezid-proc-errorlog: assert type(r) is not str, f"Unexpected return: {repr(r)}"
Jan 27 05:24:56 uc3-ezidui02x2-stg ezid-proc-errorlog: AssertionError: Unexpected return: 'DOI metadata requirements not satisfied: no publisher'
Jan 27 05:24:56 uc3-ezidui02x2-stg ezid-proc-errorlog: DEBUG ezidapp.management.commands.proc_base proc_base 26975 140261853968192 DataCite: Closing DB connections and sleeping for 1.00s...
```

**Comment by datadavev** [comment]
See also #215
