### ISSUE TITLE
Attempts to create identifiers with invalid characters should fail with error

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#213]
Example error:
```
Internal Server Error: /id/ï»¿ark:/81984/c8wd04
UnicodeEncodeError at /id/ï»¿ark:/81984/c8wd04
'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
```
This particular error appears to be a malformed URL. The response should be a 400 error (invalid request) with an appropriate message.

Also, ARK identifiers have a limited ASCII character set, and the ezid service should fail with an appropriate message attempts to create identifiers with invalid characters.

**Comment by rogerdahl** [comment]
This error occurs in a log statement. Without the log statement, I think the identifier would be correctly rejected.

I think this is an issue with default ASCII logs in Python 2. We're writing Unicode to the logs in Python 3, so this error may not occur there.
```
2022-02-04 08:02:00,096 ERROR Internal Server Error: /id/ï»¿ark:/81984/c8wd04
Traceback (most recent call last):
  File "/ezid/.pyenv/versions/ezid/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/ezid/.pyenv/versions/ezid/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/ezid/.pyenv/versions/ezid/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/ezid/.pyenv/versions/ezid/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/ezid/ezid/impl/dispatch.py", line 64, in d
    return getattr(__import__(module, fromlist=module), function)(request)
  File "/ezid/ezid/impl/api.py", line 243, in identifierDispatcher
    return _setMetadata(request)
  File "/ezid/ezid/impl/api.py", line 307, in _setMetadata
    updateExternalServices=options.get("update_external_services", True),
  File "/ezid/ezid/impl/ezid.py", line 420, in setMetadata
    nqidentifier = util.normalizeIdentifier(identifier)
  File "/ezid/ezid/impl/util.py", line 334, in normalizeIdentifier
    logger.debug('normalizeIdentifier(): {}'.format(identifier))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
--
```
