### ISSUE TITLE
`proc-link-checker` reporting validation error in `updateDatabaseTable`

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#228]
The error is:
```
Feb 28 10:47:09 uc3-ezidui02x2-stg ezid-proc-errorlog: DEBUG ezidapp.management.commands.proc_base proc_base 18803 140322062997312 LinkChecker: Entering run loop...
Feb 28 10:47:09 uc3-ezidui02x2-stg ezid-proc-errorlog: INFO ezidapp.management.commands.proc-link-checker proc-link-checker 18803 140322062997312 LinkChecker: begin update table
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: Testing stdout
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: Traceback (most recent call last):
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/ezid/ezid/manage.py", line 21, in <module>
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: main()
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/ezid/ezid/manage.py", line 17, in main
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: django.core.management.execute_from_command_line(sys.argv)
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/management/__init__.py", line 419, in execute_from_command_line
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: utility.execute()
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/management/__init__.py", line 413, in execute
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: self.fetch_command(subcommand).run_from_argv(self.argv)
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/management/base.py", line 354, in run_from_argv
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: self.execute(*args, **cmd_options)
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/management/base.py", line 398, in execute
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: output = self.handle(*args, **options)
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/apps/ezid/ezid/ezidapp/management/commands/proc_base.py", line 83, in handle
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: self.run()
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/apps/ezid/ezid/ezidapp/management/commands/proc-link-checker.py", line 116, in run
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: self.check_all()
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/apps/ezid/ezid/ezidapp/management/commands/proc-link-checker.py", line 120, in check_all
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: self.updateDatabaseTable()
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/apps/ezid/ezid/ezidapp/management/commands/proc-link-checker.py", line 333, in updateDatabaseTable
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: lc.full_clean(validate_unique=False)
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/models/base.py", line 1238, in full_clean
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: raise ValidationError(errors)
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: django.core.exceptions.ValidationError: {'target': ['Ensure this value has at most 255 characters (it has 295).']}
Feb 28 10:49:45 uc3-ezidui02x2-stg ezid-proc-errorlog: Testing stderr
```

**Comment by rogerdahl** [comment]
Error is: Ensure this value [URL target] has at most 255 characters (it has 295)

How do we want to handle it?

**Comment by datadavev** [comment]
This may be a size mismatch in the linkchecker table, since the value is already stored to be checked.

**Comment by rogerdahl** [comment]
There's a default target value that gets set from the base URL of the server. EZID on stage has a longer base URL than prod, so it generated a longer URL. Automatically generated target values are now set to always use the production instance base URL. We'll need to determine if that's what we want (knowing that the database on test instances will already have generated target values from prod).
