### ISSUE TITLE
`proc-datacite` reports an exception when processing an update

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#229]
The error is:
```
Feb 28 07:37:25 uc3-ezidui02x2-stg ezid-proc-errorlog: DEBUG ezidapp.management.commands.proc_base proc_base 31335 140710274041664 DataCite: Processing task: update
Feb 28 07:37:25 uc3-ezidui02x2-stg ezid-proc-errorlog: ERROR ezidapp.management.commands.proc-datacite proc-datacite 31335 140710274041664 DataCite: datacite.uploadMetadata returned: DOI metadata requirements not satisfied: no creator
Feb 28 07:37:25 uc3-ezidui02x2-stg ezid-proc-errorlog: ERROR ezidapp.management.commands.proc_base proc_base 31335 140710274041664 DataCite: ####################################################################################################
Feb 28 07:37:25 uc3-ezidui02x2-stg ezid-proc-errorlog: ERROR ezidapp.management.commands.proc_base proc_base 31335 140710274041664 DataCite: Exception when handling task "DataciteQueue object (3788)"
Feb 28 07:37:25 uc3-ezidui02x2-stg ezid-proc-errorlog: Traceback (most recent call last):
Feb 28 07:37:25 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/apps/ezid/ezid/ezidapp/management/commands/proc_base.py", line 105, in run
Feb 28 07:37:25 uc3-ezidui02x2-stg ezid-proc-errorlog: self.do_task(task_model)
Feb 28 07:37:25 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/apps/ezid/ezid/ezidapp/management/commands/proc_base.py", line 180, in do_task
Feb 28 07:37:25 uc3-ezidui02x2-stg ezid-proc-errorlog: self.update(task_model)
Feb 28 07:37:25 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/apps/ezid/ezid/ezidapp/management/commands/proc-datacite.py", line 28, in update
Feb 28 07:37:25 uc3-ezidui02x2-stg ezid-proc-errorlog: self._overwrite(task_model)
Feb 28 07:37:25 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/apps/ezid/ezid/ezidapp/management/commands/proc-datacite.py", line 52, in _overwrite
Feb 28 07:37:25 uc3-ezidui02x2-stg ezid-proc-errorlog: raise ezidapp.management.commands.proc_base.AsyncProcessingError(r)
Feb 28 07:37:25 uc3-ezidui02x2-stg ezid-proc-errorlog: ezidapp.management.commands.proc_base.AsyncProcessingError: DOI metadata requirements not satisfied: no creator
```

**Comment by datadavev** [comment]
The behavior appears to be correct as proc-datacite.py, line 52 raises the AsyncProcessingError due to the update being rejected by DataCite.

Need to discuss what the correct behavior should be when the update is rejected by Datacite - there's no point in retrying since it will be rejected again, so it should be removed from the task queue and perhaps available in a report to an administrator to be resolved.
