### ISSUE TITLE
proc-stats exception: `stats.recomputeStatistics FieldDoesNotExist: Identifier has no field named 'hasMetadata'`

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#276]
Exception being raised in proc-stats:

```
Traceback (most recent call last):
  File "/Users/vieglais/Documents/Projects/ezid/ezid_py3/./manage.py", line 21, in <module>
    main()
  File "/Users/vieglais/Documents/Projects/ezid/ezid_py3/./manage.py", line 17, in main
    django.core.management.execute_from_command_line(sys.argv)
  File "/Users/vieglais/.virtualenvs/ezidpy3/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/vieglais/.virtualenvs/ezidpy3/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/vieglais/.virtualenvs/ezidpy3/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/vieglais/.virtualenvs/ezidpy3/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/vieglais/Documents/Projects/ezid/ezid_py3/ezidapp/management/commands/proc_base.py", line 86, in handle
    self.run()
  File "/Users/vieglais/Documents/Projects/ezid/ezid_py3/ezidapp/management/commands/proc-stats.py", line 55, in run
    self.recomputeStatistics()
  File "/Users/vieglais/Documents/Projects/ezid/ezid_py3/ezidapp/management/commands/proc-stats.py", line 134, in recomputeStatistics
    impl.log.otherError("stats.recomputeStatistics", e)
  File "/Users/vieglais/Documents/Projects/ezid/ezid_py3/impl/log.py", line 325, in otherError
    raise exception
  File "/Users/vieglais/Documents/Projects/ezid/ezid_py3/ezidapp/management/commands/proc-stats.py", line 104, in recomputeStatistics
    qs = list(qs[:1000])
  File "/Users/vieglais/.virtualenvs/ezidpy3/lib/python3.9/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/Users/vieglais/.virtualenvs/ezidpy3/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/vieglais/.virtualenvs/ezidpy3/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/vieglais/.virtualenvs/ezidpy3/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1162, in execute_sql
    sql, params = self.as_sql()
  File "/Users/vieglais/.virtualenvs/ezidpy3/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 513, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/Users/vieglais/.virtualenvs/ezidpy3/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 55, in pre_sql_setup
    self.setup_query()
  File "/Users/vieglais/.virtualenvs/ezidpy3/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 46, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "/Users/vieglais/.virtualenvs/ezidpy3/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 227, in get_select
    cols = self.get_default_columns()
  File "/Users/vieglais/.virtualenvs/ezidpy3/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 677, in get_default_columns
    only_load = self.deferred_to_columns()
  File "/Users/vieglais/.virtualenvs/ezidpy3/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1102, in deferred_to_columns
    self.query.deferred_to_data(columns, self.query.get_loaded_field_names_cb)
  File "/Users/vieglais/.virtualenvs/ezidpy3/lib/python3.9/site-packages/django/db/models/sql/query.py", line 707, in deferred_to_data
    field = opts.get_field(parts[-1])
  File "/Users/vieglais/.virtualenvs/ezidpy3/lib/python3.9/site-packages/django/db/models/options.py", line 610, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Identifier has no field named 'hasMetadata'
```

**Comment by datadavev** [comment]
Looks like an easy fix, at `ezidapp.models.identifier.Identifier.objects.filter(` replacing `Identifier` with `SearchIdentifier`
