### ISSUE TITLE
'unhandled case' in OAI-PMH request dispatcher

### ISSUE THREAD

**Issue by rogerdahl** [CDLUC3/ezid#285]
2022-05-23 03:22:51,237    ERROR Internal Server Error: /oai
Traceback (most recent call last):
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/ezid/ezid/impl/oai.py", line 423, in dispatch
    assert False, "unhandled case"
AssertionError: unhandled case

**Comment by datadavev** [comment]
I think the issue is that when the verb is not recognized (or any other error), `_buildResponse` is returning `lxml.etree.tostring()` which is a `bytes` instance. The subsequent check in `dispatch` is testing for `str`, and so the unhandled case is reached if the request is erroneous.
