### ISSUE TITLE
IntegrityError due to attempt to insert duplicate identifier

### ISSUE THREAD

**Issue by rogerdahl** [CDLUC3/ezid#290]
Most of the instances of this exception relate to test identifiers, but not all.

```log
2022-05-23 06:38:47,242     INFO ac05d2b0da9d11ec9d2b06a406a5cd13 BEGIN createIdentifier normalizedIdentifier="ark:/99999/fk41k0wt8w" user.username="apitest" user.pid="ark:/99166/p9jq0st8j" user.group.groupname="apitest" user.group.pid="ark:/99166/p9pg1h
n29" metadata="_profile=datacite,datacite.resourcetype=Audiovisual,_status=reserved,_target=https://dc.rdc-staging.library.northwestern.edu/items/416e3fc8-f445-486a-ac84-c3582d76f180"
2022-05-23 06:38:47,242    DEBUG Checking if user can create identifier. user="apitest (EZID API test account)" prefix="ark:/99999/fk41k0wt8w"
2022-05-23 06:38:47,242    DEBUG Authorized: Is test identifier
2022-05-23 06:38:47,243    DEBUG validateIdentifier(): ark:/99999/fk41k0wt8w
2022-05-23 06:38:47,244    DEBUG validateArk(): 99999/fk41k0wt8w
2022-05-23 06:38:47,251    ERROR (1062, "Duplicate entry 'ark:/99999/fk41k0wt8w' for key 'identifier'")
2022-05-23 06:38:47,251    ERROR ac05d2b0da9d11ec9d2b06a406a5cd13 END BADREQUEST
Traceback (most recent call last):
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/mysqlclient-2.1.0-py3.8-linux-x86_64.egg/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/mysqlclient-2.1.0-py3.8-linux-x86_64.egg/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/mysqlclient-2.1.0-py3.8-linux-x86_64.egg/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry 'ark:/99999/fk41k0wt8w' for key 'identifier'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ezid/ezid/impl/ezid.py", line 290, in createIdentifier
    si.save()
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/models/base.py", line 906, in _do_insert
    return manager._insert(
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/mysqlclient-2.1.0-py3.8-linux-x86_64.egg/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/mysqlclient-2.1.0-py3.8-linux-x86_64.egg/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/mysqlclient-2.1.0-py3.8-linux-x86_64.egg/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry 'ark:/99999/fk41k0wt8w' for key 'identifier'")
```

**Comment by datadavev** [comment]
List of shoulders affected: 
```
for i in $(grep -P -o 'ERROR .*Duplicate entry .ark:/\K([0-9])*(?=/)' trace.log | sort | uniq); do echo $i; grep $i /tmp/shoulders.txt; done
63614
impl.nog.shoulder INFO     shoulder - ark:/63614/w1        Wildlife Insights (Conservation International)
81985
impl.nog.shoulder INFO     shoulder - ark:/81985/n2        NorthwesternUniv
99999
impl.nog.shoulder INFO     shoulder - ark:/99999/fk4       ARK Test
impl.nog.shoulder INFO     shoulder - ark:/99999/fk8       ARK Test (non-expiring)
```

**Comment by datadavev** [comment]
These all appear to be attempts to create identifiers through the API using identifier values that already exist. The error is an expected condition, however an exception should not be logged.

Action here is to adjust the logging message to indicate an expected condition.
