### ISSUE TITLE
DoesNotExist exceptions due to getMetadata for unknown identifier

### ISSUE THREAD

**Issue by rogerdahl** [CDLUC3/ezid#291]
```
2022-05-23 00:18:33,874     INFO 8e321080da6811ec8bda06a406a5cd13 BEGIN getMetadata ark:/99999/fk42c0hp9m anonymous anonymous anonymous anonymous False
2022-05-23 00:18:33,883    ERROR 8e321080da6811ec8bda06a406a5cd13 END BADREQUEST
Traceback (most recent call last):
  File "/ezid/ezid/impl/ezid.py", line 359, in getMetadata
    si = ezidapp.models.identifier.getIdentifier(nqidentifier, prefixMatch)
  File "/ezid/ezid/ezidapp/models/identifier.py", line 50, in getIdentifier
    return Identifier.objects.select_related(
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
ezidapp.models.identifier.Identifier.DoesNotExist: Identifier matching query does not exist.
```

**Comment by datadavev** [comment]
List of DOI prefixes in the ERROR getMetadata requests:
```
grep "ERROR .* END BADREQUEST" -B1 trace.log | grep getMetadata | grep -P -o 'doi:10\.\K([0-9])*(?=/)' | sort | uniq
13011
15784
18430
21427
5065
5067
6067
7265
7284
7289
7908
7910
7916
```
None of which are in the EZID shoulders list.

**Comment by datadavev** [comment]
Similarly for ARKs:
```
grep "ERROR .* END BADREQUEST" -B1 trace.log | grep -P -o 'getMetadata\sark:/\K([0-9])*' | sort | uniq
99999
```

**Comment by datadavev** [comment]
Looks like this is a case of excess logging, with an exception being raised inappropriately.
