### ISSUE TITLE
Encoding issue with proc-download for anvl requests

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#316]
`proc-download` is throwing an exception when a request for anvl formatted metadata is being made:

```
Jun 26 18:00:35 uc3-ezidui02x2-prd ezid-proc-errorlog: ERROR ezidapp.management.commands.proc-download 140194968704832: - ERROR download.run Exception: batch download error: error writing file: TypeError: write() argument must be str, not bytes
Jun 26 18:00:35 uc3-ezidui02x2-prd ezid-proc-errorlog: Testing stdout
Jun 26 18:00:35 uc3-ezidui02x2-prd ezid-proc-errorlog: Traceback (most recent call last):
Jun 26 18:00:35 uc3-ezidui02x2-prd ezid-proc-errorlog: File "/apps/ezid/ezid/ezidapp/management/commands/proc-download.py", line 301, in _harvest1
Jun 26 18:00:35 uc3-ezidui02x2-prd ezid-proc-errorlog: self._writeAnvl(f, id, m)
Jun 26 18:00:35 uc3-ezidui02x2-prd ezid-proc-errorlog: File "/apps/ezid/ezid/ezidapp/management/commands/proc-download.py", line 239, in _writeAnvl
Jun 26 18:00:35 uc3-ezidui02x2-prd ezid-proc-errorlog: f.write(impl.anvl.format(metadata).encode("utf-8"))
Jun 26 18:00:35 uc3-ezidui02x2-prd ezid-proc-errorlog: TypeError: write() argument must be str, not bytes
```

The issue is that the anvl write is attempting to write unicode encoded bytes to the text file:

https://github.com/CDLUC3/ezid/blob/af8b3b49422e86461baadf997a642870be2bf81d/ezidapp/management/commands/proc-download.py#L239

**Comment by datadavev** [comment]
Somewhat related to #295
