### ISSUE TITLE
Link Checker emailer and summary report

### ISSUE THREAD

**Issue by rushirajnenuji** [CDLUC3/ezid#320]
EZID Link Checker currently processes the links for existing identifiers, but the associated tools/functionalities need some fixing
- [ ] email monthly stats to the users (broken links of their existing identifiers) - [link_check_emailer.py](https://github.com/CDLUC3/ezid/blob/main/tools/link_check_emailer.py)
- [ ] email summary report to Admin (for all users) - [link_check_summary_report.py](https://github.com/CDLUC3/ezid/blob/main/tools/link_check_summary_report.py)

**Comment by datadavev** [comment]
On stage, noticed an error in `ezid-proc-error.log`:

```
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: INFO ezidapp.management.commands.proc-link-checker 140110559770432: begin load workset
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: Testing stdout
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: Traceback (most recent call last):
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/ezid/ezid/manage.py", line 21, in <module>
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: main()
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/ezid/ezid/manage.py", line 17, in main
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: django.core.management.execute_from_command_line(sys.argv)
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/management/__init__.py", line 419, in execute_from_command_line
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: utility.execute()
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/management/__init__.py", line 413, in execute
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: self.fetch_command(subcommand).run_from_argv(self.argv)
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/management/base.py", line 354, in run_from_argv
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: self.execute(*args, **cmd_options)
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/management/base.py", line 398, in execute
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: output = self.handle(*args, **options)
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/apps/ezid/ezid/ezidapp/management/commands/proc_base.py", line 86, in handle
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: self.run()
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/apps/ezid/ezid/ezidapp/management/commands/proc-link-checker.py", line 116, in run
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: self.check_all()
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/apps/ezid/ezid/ezidapp/management/commands/proc-link-checker.py", line 130, in check_all
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: self.loadWorkset()
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/apps/ezid/ezid/ezidapp/management/commands/proc-link-checker.py", line 417, in loadWorkset
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: qs = query(
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: File "/apps/ezid/ezid/ezidapp/management/commands/proc-link-checker.py", line 411, in query
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: ezidapp.models.link_checker.objects.filter(owner_id=user.id)
Jul  8 08:02:27 uc3-ezidui02x2-stg ezid-proc-errorlog: AttributeError: module 'ezidapp.models.link_checker' has no attribute 'objects'
```
