### ISSUE TITLE
Internal Server Error: `/login`

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#327]
Receiving a bunch of email notices like:
```
Internal Server Error: /login

UnreadablePostError at /login
Apache/mod_wsgi request data read error: Partial results are valid but processing is incomplete.

Request Method: POST
Request URL: http://ezid.cdlib.org/login
Django Version: 3.2.7
Python Executable: /ezid/.pyenv/versions/ezid-py3/bin/python
Python Version: 3.8.5
...

Traceback (most recent call last):
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/http/request.py", line 391, in read
    return self._stream.read(*args, **kwargs)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/wsgi.py", line 34, in read
    result = self.buffer + self._read_limited()
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/wsgi.py", line 28, in _read_limited
    result = self.stream.read(size)

The above exception (Apache/mod_wsgi request data read error: Partial results are valid but processing is incomplete.) was the direct cause of the following exception:
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/http/request.py", line 336, in body
    self._body = self.read()
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/http/request.py", line 393, in read
    raise UnreadablePostError(*e.args) from e

The above exception (Apache/mod_wsgi request data read error: Partial results are valid but processing is incomplete.) was the direct cause of the following exception:
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/ezid/ezid/impl/dispatch.py", line 54, in d
    return getattr(__import__(module, fromlist=module), function)(request)
  File "/ezid/ezid/impl/ui_account.py", line 75, in login
    "username" not in request.POST
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/wsgi.py", line 102, in _get_post
    self._load_post_and_files()
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/http/request.py", line 371, in _load_post_and_files
    self._post, self._files = QueryDict(self.body, encoding=self._encoding), MultiValueDict()
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/http/request.py", line 338, in body
    raise UnreadablePostError(*e.args) from e

Exception Type: UnreadablePostError at /login
Exception Value: Apache/mod_wsgi request data read error: Partial results are valid but processing is incomplete.
Request information:
USER: AnonymousUser

GET: No GET data

POST: No POST data

FILES: No FILES data

COOKIES: No cookie data
```

**Comment by datadavev** [comment]
Also related includes `/status` errors, like: 
```
Traceback (most recent call last):
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/ezid/ezid/impl/api.py", line 403, in getStatus
    return _response("success: " + statusLine, anvlBody=body)

Exception Type: TypeError at /status
Exception Value: can only concatenate str (not "bytes") to str
```

**Comment by datadavev** [comment]
and `/contact`:
```
   Traceback (most recent call last):
      File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/http/request.py", line 391, in read
        return self._stream.read(*args, **kwargs)
      File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/wsgi.py", line 34, in read
        result = self.buffer + self._read_limited()
      File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/wsgi.py", line 28, in _read_limited
        result = self.stream.read(size)

    The above exception (Apache/mod_wsgi request data read error: Partial results are valid but processing is incomplete.) was the direct cause of the following exception:
      File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/http/request.py", line 336, in body
        self._body = self.read()
      File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/http/request.py", line 393, in read
        raise UnreadablePostError(*e.args) from e

    The above exception (Apache/mod_wsgi request data read error: Partial results are valid but processing is incomplete.) was the direct cause of the following exception:
      File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/exception.py", line 47, in inner
        response = get_response(request)
      File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/base.py", line 181, in _get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/ezid/ezid/impl/ui.py", line 42, in contact
        P = request.POST
      File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/wsgi.py", line 102, in _get_post
        self._load_post_and_files()
      File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/http/request.py", line 371, in _load_post_and_files
        self._post, self._files = QueryDict(self.body, encoding=self._encoding), MultiValueDict()
      File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/http/request.py", line 338, in body
        raise UnreadablePostError(*e.args) from e

```
