### ISSUE TITLE
Internal server error raised on invalid post data

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#336]
An internal server error is being raised when POST is sent to `/`. This should be handled more elegantly and simply logged as an invalid request.

```
On 8/14/22, 4:59 PM, "ezid@uc3-ezidui02x2-prd.cdlib.org" <ezid@uc3-ezidui02x2-prd.cdlib.org> wrote:

    Internal Server Error: /

    UnreadablePostError at /
    Apache/mod_wsgi request data read error: Partial results are valid but processing is incomplete.

    Request Method: POST
    Request URL: http://35.164.191.218/
    Django Version: 3.2.7
    Python Executable: /ezid/.pyenv/versions/ezid-py3/bin/python
    Python Version: 3.8.5

    Traceback (most recent call last):
      File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/http/request.py", line 391, in read
        return self._stream.read(*args, **kwargs)
      File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/wsgi.py", line 34, in read
        result = self.buffer + self._read_limited()
      File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/wsgi.py", line 28, in _read_limited
        result = self.stream.read(size)

    The above exception (Apache/mod_wsgi request data read error: Partial results are valid but processing is incomplete.) was the direct cause of the following exception:
      File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/http/request.py", line 336, in body
        self._body = self.read()
      File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/http/request.py", line 393, in read
        raise UnreadablePostError(*e.args) from e

    The above exception (Apache/mod_wsgi request data read error: Partial results are valid but processing is incomplete.) was the direct cause of the following exception:
      File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/exception.py", line 47, in inner
        response = get_response(request)
      File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/base.py", line 181, in _get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/ezid/ezid/impl/ui_home.py", line 26, in index
        d = impl.ui_create.simple_form(request, d)
      File "/ezid/ezid/impl/ui_create.py", line 99, in simple_form
        REQUEST = request.POST
      File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/wsgi.py", line 102, in _get_post
        self._load_post_and_files()
      File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/http/request.py", line 371, in _load_post_and_files
        self._post, self._files = QueryDict(self.body, encoding=self._encoding), MultiValueDict()
      File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/http/request.py", line 338, in body
        raise UnreadablePostError(*e.args) from e

    Exception Type: UnreadablePostError at /
    Exception Value: Apache/mod_wsgi request data read error: Partial results are valid but processing is incomplete.
    Request information:
    USER: AnonymousUser

    GET: No GET data

    POST: No POST data

    FILES: No FILES data

    COOKIES: No cookie data
```

**Comment by datadavev** [comment]
It appears this may be indicative of service performance, where a client is uploading content, server starts processing but is slow (perhaps a middleware hook?) and the client disconnects before the service is able to read the remainder of the post data.

**Comment by rushirajnenuji** [comment]
Solved with the new ALB WAF rules
