### ISSUE TITLE
`Internal Server Error: /account/pwreset` raised when password reset attempted

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#341]
```
Internal Server Error: /account/pwreset

AttributeError at /account/pwreset
'str' object has no attribute 'primaryContactName'

Request Method: POST
Request URL: http://ezid.cdlib.org/account/pwreset
Django Version: 3.2.7
Python Executable: /ezid/.pyenv/versions/ezid-py3/bin/python
Python Version: 3.8.5
...
Traceback (most recent call last):
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/ezid/ezid/impl/ui_account.py", line 396, in pwreset
    r = sendPasswordResetEmail(request, username, email)
  File "/ezid/ezid/impl/ui_account.py", line 442, in sendPasswordResetEmail
    _sendEmail(request, username, _("EZID password reset request"), message, emailAddress)
  File "/ezid/ezid/impl/ui_account.py", line 249, in _sendEmail
    to_full_address = user.primaryContactName + "<" + to_address + ">"

Exception Type: AttributeError at /account/pwreset
Exception Value: 'str' object has no attribute 'primaryContactName'
Request information:
USER: AnonymousUser

GET: No GET data

POST:
username = 'ucnrs_kwong'
email = 'kathleen.wong@ucop.edu'

FILES: No FILES data

COOKIES: No cookie data
```

**Comment by mariagould** [comment]
I just reproduced this on my end. The password reset link throws the error above and presents users with the message in the screenshot). 

![Screen Shot 2022-09-12 at 10 32 18 AM](https://user-images.githubusercontent.com/45110557/189719404-dea4006d-a4e7-47f5-b7e1-baf06819ab48.png)


Changing the password while logged in does not appear to generate the same issue.
