### ISSUE TITLE
Fix issues with downserver

### ISSUE THREAD

**Issue by rushirajnenuji** [CDLUC3/ezid#363]
During MySQL upgrade today, we noticed that the down server is broken after Pyhton3 upgrade. 

Errorlog:

```
----------------------------------------
172.30.8.249 - - [17/Nov/2022 05:23:11] "GET /id/ark:/87607/c7930pg8d HTTP/1.1" 503 -
----------------------------------------
Exception happened during processing of request from ('172.30.8.249', 32564)
Traceback (most recent call last):
  File "/ezid/.pyenv/versions/3.8.5/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/ezid/.pyenv/versions/3.8.5/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/ezid/.pyenv/versions/3.8.5/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/ezid/.pyenv/versions/3.8.5/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/ezid/.pyenv/versions/3.8.5/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/apps/ezid/ezid/tools/downserver.py", line 154, in do_GET
    self.sendResponse(503, "text/plain", len(message) + 7, "error: " + message)
  File "/apps/ezid/ezid/tools/downserver.py", line 140, in sendResponse
    self.wfile.write(content.encode())
  File "/ezid/.pyenv/versions/3.8.5/lib/python3.8/socketserver.py", line 799, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'
----------------------------------------
```

**Comment by rushirajnenuji** [comment]
Deployed a fix in [v3.0.14](https://github.com/CDLUC3/ezid/releases/tag/3.0.14)
