### ISSUE TITLE
Handle `pwreset` errors a bit more elegantly

### ISSUE THREAD

**Issue by datadavev** [CDLUC3/ezid#369]
The `pwreset` form is necessarily exposed to the Internet. Some bots latch onto this and submit content apparently designed for disruption. These are correctly handled as error conditions, but they can result in exceptions being raised and so trigger email alerts.

Task here is to more elegantly handle such condition so as not to trigger unnecessary email notification.

Example, note the username and email towards the end:
```
nternal Server Error: /account/pwreset

OperationalError at /account/pwreset
(1267, "Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,COERCIBLE) for operation '='")

Request Method: POST
Request URL: http://ezid.cdlib.org/account/pwreset
Django Version: 3.2.7
Python Executable: /ezid/.pyenv/versions/ezid-py3/bin/python
Python Version: 3.8.5
...
Traceback (most recent call last):
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/mysqlclient-2.1.0-py3.8-linux-x86_64.egg/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/mysqlclient-2.1.0-py3.8-linux-x86_64.egg/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/mysqlclient-2.1.0-py3.8-linux-x86_64.egg/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)

The above exception ((1267, "Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,COERCIBLE) for operation '='")) was the direct cause of the following exception:
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/ezid/ezid/impl/ui_account.py", line 396, in pwreset
    r = sendPasswordResetEmail(request, username, email)
  File "/ezid/ezid/impl/ui_account.py", line 413, in sendPasswordResetEmail
    user = ezidapp.models.util.getUserByUsername(username)
  File "/ezid/ezid/ezidapp/models/util.py", line 50, in getUserByUsername
    return _getUserPrefetch(username=username)
  File "/ezid/ezid/ezidapp/models/util.py", line 19, in _getUserPrefetch
    user_model.objects.select_related("group", "realm")
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/mysqlclient-2.1.0-py3.8-linux-x86_64.egg/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/mysqlclient-2.1.0-py3.8-linux-x86_64.egg/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/mysqlclient-2.1.0-py3.8-linux-x86_64.egg/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)

Exception Type: OperationalError at /account/pwreset
Exception Value: (1267, "Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,COERCIBLE) for operation '='")
Request information:
USER: AnonymousUser

GET: No GET data

POST:
username = '\ufeffArtificial intelligence creates content for the site, no worse than a copywriter, you can also use it to write articles. 100% uniqueness,7-day free trial of Pro Plan, No credit card required:). Click Here:👉 https://stanford.io/3V6fSRi?h=7a7965b2906130f1086b648e5f8c89b3&'
email = 'nickterp@gmailwe.com'

```

**Comment by rushirajnenuji** [comment]
Solved with the new ALB WAF rules
