### ISSUE TITLE
Minter migration on ezid-stg

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#482]
Stage migration checklist:

- [x] Make sure the deployment procedure is in place
- [x] Make sure the rollback procedure is in place
- [x] Perform instance health check  - at least 3 days before the migration
- [x] Perform EZID health check  - at least 3 days before the migration
- [x] Perform minter health check - at least 3 days before the migration
- [x] Schedule downtime
- [x] Create IAS ticket for shutdown, backup, restart RDS and  disable/enable Nagios
- [x] Communicate downtime to EZID users
- [x] Stop Nagios alerts
- [x] Stop EZID and background jobs
- [x] Stop EZID database, take a backup, restart the database
- [x] Backup BDB minters
- [x] Get updated code
- [x] Perform data model migration
- [x] Perform BDB Minter data migration
- [x] Test minter - run the `diag-minter` command to mint identifiers on test shoulders
- [x] Start EZID
- [x] Test EZID - run the `check-ezid` command to test: create shoulder, mint/create/update IDs
- [x] Start background jobs
- [x] Run the `verify_ezid_after_patching.py` script to verify  EZID services
- [x] Restore Nagios  alterts
- [x] Announce migration completion

**Comment by jsjiang** [comment]
IAS ticket for RDS backup and disable/enable Nagios alerts: https://github.com/cdlib/cdlsys/issues/291

**Comment by jsjiang** [comment]
Disk space  check:
* 30% used on `/apps/ezid`, available 11GB

EZID error check:

**Comment by jsjiang** [comment]
Issues:
* Failed to restart the crossref  queue service
  * started initially but reported error after trying to restart  
  * Error message from   cdlsysctl command: “start request repeated too quickly for ezid-proc-crossref.service”
  * Errors from `sudo journalctl -u ezid-proc-crossref -r`

```
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    django.core.management.execute_from_command_line(sys.argv)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/apps/ezid/ezid/ezidapp/management/commands/proc_base.py", line 94, in handle
    self.run()
  File "/apps/ezid/ezid/ezidapp/management/commands/proc-crossref.py", line 72, in run
    log.info(f'Processing task: {str(task_model)}')
  File "/apps/ezid/ezid/ezidapp/models/async_queue.py", line 32, in __str__
    f'{self.__class__.__name__}('
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/models/fields/related_descriptors.py", line 187, in __get__
    rel_obj = self.get_object(instance)
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/models/fields/related_descriptors.py", line 154, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "/ezid/.pyenv/versions/ezid-py3/lib/python3.8/site-packages/Django-3.2.7-py3.8.egg/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
ezidapp.models.identifier.DoesNotExist: RefIdentifier matching query does not exist.
```

This error was caused by data discrepancy: 
* record seq=186905, refidentifier_id = 37905382 is in the crossref queue with status='C-UNCHECK', but the identifier id  is not in the refidentifier table.
* Fix: manually changed the status to 'F' and noted in  the message field 'jing: updated status fro  C to F'
* Future refactor: add error handling to report this kind of error but continue the process

```
select *  from `ezidapp_crossrefqueue` 
where status in ('U','C', 'S')
and refidentifier_id not in (
select  id from  ezidapp_refidentifier );  => 1  record

select * from ezidapp_refidentifier where id = 37905382; => No

select * from ezidapp_identifier where id = 37905382; =>  No

select *, from_unixtime(enqueuetime), from_unixtime(submittime)  from `ezidapp_crossrefqueue`  where refidentifier_id = 37905382; 

seq	enqueueTime	submitTime	operation	status	message	batchId	error	errorIsPermanent	refIdentifier_id	from_unixtime(enqueuetime)	from_unixtime(submittime)
186905	1699402758	1699402759	C	F	jing: updated status fro  C to F	755586e2-7dcc-11ee-bc61-0a0c7ad0442b		0	37905382	2023-11-07 16:19:18	2023-11-07 16:19:19

```

**Comment by jsjiang** [comment]
RDS backup: rds-ias-ezid-search3-stg-20231107-issue291
