### ISSUE TITLE
Look into crash in /dow/download_error

### ISSUE THREAD

**Issue by rogerdahl** [CDLUC3/ezid#53]
```
2020-09-29 09:44:43,577 WARNING Not Found: /phpmyadmin2222/index.php
2020-09-29 09:44:45,786 WARNING Not Found: /phpMyAdmin333/index.php
2020-09-29 09:44:46,185 WARNING Not Found: /phpmyadmin3333/index.php
2020-09-29 09:44:47,573 WARNING Not Found: /php2MyAdmin/index.php
2020-09-29 09:44:47,972 WARNING Not Found: /phpiMyAdmin/index.php
2020-09-29 09:44:48,363 WARNING Not Found: /phpNyAdmin/index.php
2020-09-29 09:44:48,757 WARNING Not Found: /1/index.php
2020-09-29 09:44:49,158 ERROR Internal Server Error: /dow/download_error
Traceback (most recent call last):
  File "/apps/ezid/.pyenv/versions/ezid/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/apps/ezid/.pyenv/versions/ezid/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/apps/ezid/.pyenv/versions/ezid/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/apps/ezid/.pyenv/versions/ezid/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/apps/ezid/ezid/impl/ui_manage.py", line 521, in download_error
    return uic.error(request, 404, content)
  File "/apps/ezid/ezid/impl/ui_common.py", line 195, in error
    content = templates[str(code)][0].render(t)
  File "/apps/ezid/.pyenv/versions/ezid/lib/python2.7/site-packages/django/template/backends/django.py", line 64, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "/apps/ezid/.pyenv/versions/ezid/lib/python2.7/site-packages/django/template/context.py", line 287, in make_context
    raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than RequestContext.
2020-09-29 09:44:49,598 WARNING Not Found: /phpMyAdmin_111/index.php
2020-09-29 09:44:49,995 WARNING Not Found: /phpmadmin/index.php
2020-09-29 09:44:50,399 WARNING Not Found: /321/index.php
2020-09-29 09:44:50,802 WARNING Not Found: /123131/index.php
2020-09-29 09:44:51,778 WARNING Not Found: /phpMyAdminn/index.php
2020-09-29 09:45:07,566 WARNING Not Found: /phpMyAdmln/index.php
```

**Comment by rogerdahl** [comment]
This exception was caused by template instead of dict being passed to render(), and was fixed when we removed caching of templates.

`content = templates[str(code)][0].render(t)`

has been replaced with

 `content = templ.render(ctx, request=request)`

where `ctx` is the required dict.
